
options = {"cheese" : 10,
	"pepperoni" : 11,
	"meat lovers" : 12,
	"hawaiian" : 11,
    "meatball" : 11,
	"white" : 13,
    "chicken" : 14,
    "veggie" : 10,
    "bacon" : 12,
    "the benjamin" : 100,
	"eggplant" : 9,
    "sausage" : 7,
    "salad" : 9,
    "coke" : 2,
    "sprite" : 2}
